import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import {
  OrgApiError,
  WORKBENCH_SESSION_LIST_SCHEMA_VERSION,
  WORKBENCH_SESSION_SCHEMA_VERSION,
  errorCodes,
  isPositionId,
} from "@org-workbench/shared";
import type { WorkbenchSession, WorkbenchSessionList } from "@org-workbench/shared";
import { StableReadError, decodeStableUtf8, readStableBoundedFile } from "../stable-read.js";
import { atomicWriteJson, nodeAtomicTurnWriteOperations } from "../turns/store.js";

const SESSION_ROOT_SEGMENTS = [".digital-employee", "workbench", "sessions"];
const POSITIONS_SEGMENT = "positions";
const WORKSPACE_RECORD = "workspace-instance.json";
const WORKSPACE_SCHEMA_VERSION = "workspace-instance.v1";
const POSITION_SCHEMA_VERSION = "session-position-state.v1";
const MAX_POSITION_RECORD_BYTES = 4 * 1024 * 1024;
const MAX_WORKSPACE_RECORD_BYTES = 16 * 1024;
const MAX_POSITIONS = 1024;
const MAX_SESSIONS_PER_POSITION = 128;
const MAX_POSITION_TEMP_FILES = MAX_POSITIONS;
const MAX_POSITION_DIRECTORY_ENTRIES = MAX_POSITIONS + MAX_POSITION_TEMP_FILES;
const MAX_AUTHORITATIVE_POSITION_BYTES = 64 * 1024 * 1024;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

interface WorkspaceInstanceRecord {
  schemaVersion: typeof WORKSPACE_SCHEMA_VERSION;
  workspaceInstanceId: string;
  createdAt: string;
}

interface PositionSessionState {
  schemaVersion: typeof POSITION_SCHEMA_VERSION;
  workspaceInstanceId: string;
  positionId: string;
  activeSessionId: string | null;
  sessions: WorkbenchSession[];
}

export interface AuthoritativeSessionIndex {
  workspaceInstanceId: string;
  sessions: ReadonlyMap<string, WorkbenchSession>;
}

export interface RotateResult {
  session: WorkbenchSession;
  created: boolean;
}

function sessionError(message: string): OrgApiError {
  return new OrgApiError(errorCodes.session_storage_failed, 500, message);
}

function sessionMissing(): OrgApiError {
  return new OrgApiError(errorCodes.session_missing, 404, "session not found in the open workspace");
}

function sessionConflict(message: string): OrgApiError {
  return new OrgApiError(errorCodes.session_conflict, 409, message);
}

export function assertSessionId(value: unknown): string {
  if (typeof value !== "string" || !UUID_PATTERN.test(value)) {
    throw new OrgApiError(
      errorCodes.session_request_invalid,
      400,
      "sessionId must be an opaque UUID generated by the server",
    );
  }
  return value;
}

function assertPositionId(value: unknown): string {
  if (!isPositionId(value)) {
    throw new OrgApiError(errorCodes.session_request_invalid, 400, "positionId is invalid");
  }
  return value;
}

function sessionsRoot(workspace: string): string {
  return path.join(workspace, ...SESSION_ROOT_SEGMENTS);
}

function positionsDir(workspace: string): string {
  return path.join(sessionsRoot(workspace), POSITIONS_SEGMENT);
}

function positionFile(workspace: string, positionId: string): string {
  assertPositionId(positionId);
  const root = path.resolve(positionsDir(workspace));
  const file = path.resolve(root, `${positionId}.json`);
  if (path.dirname(file) !== root) throw sessionError("session position path escapes its state root");
  return file;
}

function hasExactKeys(value: Record<string, unknown>, expected: string[]): boolean {
  return Object.keys(value).sort().join(",") === [...expected].sort().join(",");
}

function validTimestamp(value: unknown): value is string {
  return typeof value === "string" && value.length <= 64 && Number.isFinite(Date.parse(value));
}

function isWorkspaceRecord(value: unknown): value is WorkspaceInstanceRecord {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return hasExactKeys(record, ["schemaVersion", "workspaceInstanceId", "createdAt"]) &&
    record.schemaVersion === WORKSPACE_SCHEMA_VERSION &&
    typeof record.workspaceInstanceId === "string" && UUID_PATTERN.test(record.workspaceInstanceId) &&
    validTimestamp(record.createdAt);
}

function isWorkbenchSession(value: unknown): value is WorkbenchSession {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  if (!hasExactKeys(record, [
    "schemaVersion", "sessionId", "workspaceInstanceId", "positionId", "principal",
    "status", "rotatedFrom", "rotatedTo", "createdAt", "rotatedAt",
  ])) return false;
  if (
    record.schemaVersion !== WORKBENCH_SESSION_SCHEMA_VERSION ||
    typeof record.sessionId !== "string" || !UUID_PATTERN.test(record.sessionId) ||
    typeof record.workspaceInstanceId !== "string" || !UUID_PATTERN.test(record.workspaceInstanceId) ||
    !isPositionId(record.positionId) || record.principal !== `position.${record.positionId}` ||
    (record.status !== "active" && record.status !== "rotated") ||
    (record.rotatedFrom !== null && (typeof record.rotatedFrom !== "string" || !UUID_PATTERN.test(record.rotatedFrom))) ||
    (record.rotatedTo !== null && (typeof record.rotatedTo !== "string" || !UUID_PATTERN.test(record.rotatedTo))) ||
    !validTimestamp(record.createdAt) ||
    (record.rotatedAt !== null && !validTimestamp(record.rotatedAt))
  ) return false;
  if (record.status === "active" && (record.rotatedTo !== null || record.rotatedAt !== null)) return false;
  if (record.status === "rotated" && (record.rotatedTo === null || record.rotatedAt === null)) return false;
  return true;
}

function isPositionState(
  value: unknown,
  expectedPositionId: string,
  expectedWorkspaceInstanceId: string,
): value is PositionSessionState {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  if (!hasExactKeys(record, [
    "schemaVersion", "workspaceInstanceId", "positionId", "activeSessionId", "sessions",
  ])) return false;
  if (
    record.schemaVersion !== POSITION_SCHEMA_VERSION ||
    record.workspaceInstanceId !== expectedWorkspaceInstanceId ||
    record.positionId !== expectedPositionId ||
    (record.activeSessionId !== null &&
      (typeof record.activeSessionId !== "string" || !UUID_PATTERN.test(record.activeSessionId))) ||
    !Array.isArray(record.sessions) || record.sessions.length > MAX_SESSIONS_PER_POSITION ||
    !record.sessions.every(isWorkbenchSession)
  ) return false;
  const sessions = record.sessions as WorkbenchSession[];
  const byId = new Map<string, WorkbenchSession>();
  for (const session of sessions) {
    if (
      byId.has(session.sessionId) ||
      session.positionId !== expectedPositionId ||
      session.workspaceInstanceId !== expectedWorkspaceInstanceId
    ) return false;
    byId.set(session.sessionId, session);
  }
  const active = sessions.filter((session) => session.status === "active");
  if (active.length !== (sessions.length === 0 ? 0 : 1)) return false;
  if ((active[0]?.sessionId ?? null) !== record.activeSessionId) return false;
  for (const session of sessions) {
    if (session.rotatedTo !== null) {
      const successor = byId.get(session.rotatedTo);
      if (!successor || successor.rotatedFrom !== session.sessionId) return false;
    }
    if (session.rotatedFrom !== null) {
      const predecessor = byId.get(session.rotatedFrom);
      if (!predecessor || predecessor.rotatedTo !== session.sessionId) return false;
    }
  }
  if (sessions.length > 0) {
    const roots = sessions.filter((session) => session.rotatedFrom === null);
    if (roots.length !== 1) return false;
    const visited = new Set<string>();
    let cursor: WorkbenchSession | undefined = roots[0];
    while (cursor) {
      if (visited.has(cursor.sessionId)) return false;
      visited.add(cursor.sessionId);
      cursor = cursor.rotatedTo === null ? undefined : byId.get(cursor.rotatedTo);
    }
    if (visited.size !== sessions.length || !active[0] || !visited.has(active[0].sessionId)) return false;
  }
  return true;
}

async function ensureRealDirectories(workspace: string): Promise<void> {
  const root = path.resolve(workspace);
  const rootStat = await fs.lstat(root);
  if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) {
    throw sessionError("workspace must be a real directory for local session state");
  }
  let current = root;
  for (const segment of [...SESSION_ROOT_SEGMENTS, POSITIONS_SEGMENT]) {
    current = path.join(current, segment);
    try {
      const stat = await fs.lstat(current);
      if (!stat.isDirectory() || stat.isSymbolicLink()) {
        throw sessionError("local session state path must not contain symbolic links");
      }
    } catch (error) {
      if (error instanceof OrgApiError) throw error;
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw sessionError("local session state path is unreadable");
      try {
        await fs.mkdir(current, { mode: 0o700 });
      } catch (mkdirError) {
        if ((mkdirError as NodeJS.ErrnoException).code !== "EEXIST") {
          throw sessionError("local session state directory could not be created");
        }
      }
      const created = await fs.lstat(current);
      if (!created.isDirectory() || created.isSymbolicLink()) {
        throw sessionError("local session directory creation raced with an unsafe path");
      }
    }
    if (segment !== ".digital-employee") await fs.chmod(current, 0o700);
  }
}

interface BoundedJsonRead {
  value: unknown;
  bytes: number;
}

async function readBoundedFile(file: string, maxBytes: number) {
  try {
    return await readStableBoundedFile(file, maxBytes);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") throw error;
    if (error instanceof StableReadError) {
      throw sessionError("local session record is not a stable bounded regular file");
    }
    throw sessionError("local session record is unreadable");
  }
}

async function readBoundedJson(
  file: string,
  maxBytes: number,
  beforeParse?: (bytes: number) => void,
): Promise<BoundedJsonRead> {
  const stable = await readBoundedFile(file, maxBytes);
  beforeParse?.(stable.bytes);
  try {
    return { value: JSON.parse(decodeStableUtf8(stable.buffer)) as unknown, bytes: stable.bytes };
  } catch {
    throw sessionError("local session record is not valid JSON");
  }
}

function atomicTemporaryTarget(name: string): string | null {
  if (!name.startsWith(".") || !name.endsWith(".tmp")) return null;
  const stem = name.slice(1, -4);
  if (stem.length <= 37 || stem.at(-37) !== ".") return null;
  const nonce = stem.slice(-36);
  if (!UUID_PATTERN.test(nonce)) return null;
  const target = stem.slice(0, -37);
  return target.length > 0 ? target : null;
}

function isPositionStateTemporary(name: string): boolean {
  const target = atomicTemporaryTarget(name);
  return target !== null && target.endsWith(".json") && isPositionId(target.slice(0, -5));
}

async function assertExistingSessionStateDirectories(workspace: string): Promise<void> {
  let current = path.resolve(workspace);
  for (const segment of [...SESSION_ROOT_SEGMENTS, POSITIONS_SEGMENT]) {
    let stat;
    try {
      stat = await fs.lstat(current);
    } catch {
      throw sessionError("authoritative session state path is unreadable");
    }
    if (!stat.isDirectory() || stat.isSymbolicLink()) {
      throw sessionError("authoritative session state path is unsafe");
    }
    current = path.join(current, segment);
  }
  let stat;
  try {
    stat = await fs.lstat(current);
  } catch {
    throw sessionError("authoritative session state path is unreadable");
  }
  if (!stat.isDirectory() || stat.isSymbolicLink()) {
    throw sessionError("authoritative session state path is unsafe");
  }
}

/** Read-only authoritative session identity used by derived reporting views.
 * It consumes the same frozen workspace/position/session validators as the
 * lifecycle store and never creates, chmods, or repairs local state. */
export async function readAuthoritativeSessionIndex(
  workspace: string,
): Promise<AuthoritativeSessionIndex> {
  await assertExistingSessionStateDirectories(workspace);
  const identityRead = await readBoundedJson(
    path.join(sessionsRoot(workspace), WORKSPACE_RECORD),
    MAX_WORKSPACE_RECORD_BYTES,
  );
  const identity = identityRead.value;
  if (!isWorkspaceRecord(identity)) {
    throw sessionError("authoritative workspace session identity is invalid");
  }

  let entries;
  try {
    entries = await fs.readdir(positionsDir(workspace), { withFileTypes: true });
  } catch {
    throw sessionError("authoritative session position index is unreadable");
  }
  if (entries.length > MAX_POSITION_DIRECTORY_ENTRIES) {
    throw sessionError("authoritative session position index exceeds its entry bound");
  }

  let positionCount = 0;
  let temporaryCount = 0;
  let totalBytes = 0;
  const chargePositionBytes = (bytes: number): void => {
    totalBytes += bytes;
    if (totalBytes > MAX_AUTHORITATIVE_POSITION_BYTES) {
      throw sessionError("authoritative session position index exceeds its byte budget");
    }
  };
  const sessions = new Map<string, WorkbenchSession>();
  for (const entry of entries) {
    const file = path.join(positionsDir(workspace), entry.name);
    if (entry.name.endsWith(".tmp")) {
      temporaryCount += 1;
      if (
        temporaryCount > MAX_POSITION_TEMP_FILES ||
        !isPositionStateTemporary(entry.name) ||
        !entry.isFile() ||
        entry.isSymbolicLink()
      ) {
        throw sessionError("authoritative session position index contains an unsafe temporary");
      }
      const temporary = await readBoundedFile(file, MAX_POSITION_RECORD_BYTES);
      chargePositionBytes(temporary.bytes);
      continue;
    }

    positionCount += 1;
    if (
      positionCount > MAX_POSITIONS ||
      !entry.isFile() ||
      entry.isSymbolicLink() ||
      !entry.name.endsWith(".json")
    ) {
      throw sessionError("authoritative session position index contains an unsafe record");
    }
    const positionId = entry.name.slice(0, -5);
    if (!isPositionId(positionId)) {
      throw sessionError("authoritative session position index contains an unsafe id");
    }
    const { value: raw } = await readBoundedJson(
      file,
      MAX_POSITION_RECORD_BYTES,
      chargePositionBytes,
    );
    if (!isPositionState(raw, positionId, identity.workspaceInstanceId)) {
      throw sessionError("authoritative session position state is invalid");
    }
    for (const session of raw.sessions) {
      if (sessions.has(session.sessionId)) {
        throw sessionError("authoritative session id is duplicated across positions");
      }
      sessions.set(session.sessionId, session);
    }
  }
  return { workspaceInstanceId: identity.workspaceInstanceId, sessions };
}

export class SessionStore {
  private readonly locks = new Map<string, Promise<void>>();
  private readonly activeTurns = new Map<string, number>();

  async create(workspace: string, positionId: string, now = new Date().toISOString()): Promise<WorkbenchSession> {
    assertPositionId(positionId);
    return this.exclusive(`position\0${path.resolve(workspace)}\0${positionId}`, async () => {
      const identity = await this.workspaceIdentity(workspace, now);
      const existing = await this.readPositionStateIfPresent(workspace, positionId, identity.workspaceInstanceId);
      if (existing?.activeSessionId !== null && existing?.activeSessionId !== undefined) {
        throw sessionConflict("position already has an active session; rotate it explicitly");
      }
      return this.createSessionRecord(workspace, positionId, identity.workspaceInstanceId, existing, now);
    });
  }

  /** #116: an eager anchor (group create) adopts the position's active session
   * when one already exists and writes nothing, so the member's personal
   * lifecycle stays intact; it creates a session only where none is active. */
  async reuseOrCreateActive(
    workspace: string,
    positionId: string,
    now = new Date().toISOString(),
  ): Promise<WorkbenchSession> {
    assertPositionId(positionId);
    return this.exclusive(`position\0${path.resolve(workspace)}\0${positionId}`, async () => {
      const identity = await this.workspaceIdentity(workspace, now);
      const existing = await this.readPositionStateIfPresent(workspace, positionId, identity.workspaceInstanceId);
      const active = existing?.sessions.find((session) => session.status === "active");
      if (active) return active;
      return this.createSessionRecord(workspace, positionId, identity.workspaceInstanceId, existing, now);
    });
  }

  /** Runs under the position lock with the current state already read. */
  private async createSessionRecord(
    workspace: string,
    positionId: string,
    workspaceInstanceId: string,
    existing: PositionSessionState | null,
    now: string,
  ): Promise<WorkbenchSession> {
    if ((existing?.sessions.length ?? 0) >= MAX_SESSIONS_PER_POSITION) {
      throw sessionError("position session history reached its bounded record count");
    }
    const session: WorkbenchSession = {
      schemaVersion: WORKBENCH_SESSION_SCHEMA_VERSION,
      sessionId: crypto.randomUUID(),
      workspaceInstanceId,
      positionId,
      principal: `position.${positionId}`,
      status: "active",
      rotatedFrom: null,
      rotatedTo: null,
      createdAt: now,
      rotatedAt: null,
    };
    const state: PositionSessionState = {
      schemaVersion: POSITION_SCHEMA_VERSION,
      workspaceInstanceId,
      positionId,
      activeSessionId: session.sessionId,
      sessions: [...(existing?.sessions ?? []), session],
    };
    await atomicWriteJson(positionFile(workspace, positionId), state, MAX_POSITION_RECORD_BYTES, nodeAtomicTurnWriteOperations);
    return session;
  }

  async list(workspace: string, positionId: string): Promise<WorkbenchSessionList> {
    assertPositionId(positionId);
    const identity = await this.workspaceIdentity(workspace);
    const state = await this.readPositionStateIfPresent(workspace, positionId, identity.workspaceInstanceId);
    return {
      schemaVersion: WORKBENCH_SESSION_LIST_SCHEMA_VERSION,
      positionId,
      activeSessionId: state?.activeSessionId ?? null,
      sessions: [...(state?.sessions ?? [])].sort((left, right) =>
        right.createdAt === left.createdAt
          ? right.sessionId.localeCompare(left.sessionId, "en")
          : right.createdAt.localeCompare(left.createdAt, "en")),
    };
  }

  async get(workspace: string, sessionId: string): Promise<WorkbenchSession> {
    assertSessionId(sessionId);
    const found = await this.find(workspace, sessionId);
    if (!found) throw sessionMissing();
    return found.session;
  }

  async rotate(
    workspace: string,
    sessionId: string,
    now = new Date().toISOString(),
  ): Promise<RotateResult> {
    assertSessionId(sessionId);
    return this.exclusive(`session\0${path.resolve(workspace)}\0${sessionId}`, async () => {
      if ((this.activeTurns.get(this.turnKey(workspace, sessionId)) ?? 0) > 0) {
        throw sessionConflict("session has a running turn and cannot be rotated");
      }
      const found = await this.find(workspace, sessionId);
      if (!found) throw sessionMissing();
      const source = found.session;
      if (source.status === "rotated") {
        const successor = found.state.sessions.find((candidate) => candidate.sessionId === source.rotatedTo);
        if (!successor) throw sessionError("rotated session successor is missing");
        return { session: successor, created: false };
      }
      if (found.state.activeSessionId !== source.sessionId) {
        throw sessionConflict("only the active session can be rotated");
      }
      if (found.state.sessions.length >= MAX_SESSIONS_PER_POSITION) {
        throw sessionError("position session history reached its bounded record count");
      }
      const nextId = crypto.randomUUID();
      const rotated: WorkbenchSession = {
        ...source,
        status: "rotated",
        rotatedTo: nextId,
        rotatedAt: now,
      };
      const successor: WorkbenchSession = {
        schemaVersion: WORKBENCH_SESSION_SCHEMA_VERSION,
        sessionId: nextId,
        workspaceInstanceId: source.workspaceInstanceId,
        positionId: source.positionId,
        principal: source.principal,
        status: "active",
        rotatedFrom: source.sessionId,
        rotatedTo: null,
        createdAt: now,
        rotatedAt: null,
      };
      const state: PositionSessionState = {
        ...found.state,
        activeSessionId: successor.sessionId,
        sessions: found.state.sessions.map((candidate) =>
          candidate.sessionId === source.sessionId ? rotated : candidate).concat(successor),
      };
      await atomicWriteJson(positionFile(workspace, source.positionId), state, MAX_POSITION_RECORD_BYTES, nodeAtomicTurnWriteOperations);
      return { session: successor, created: true };
    });
  }

  async reserveTurn(workspace: string, sessionId: string): Promise<WorkbenchSession> {
    assertSessionId(sessionId);
    return this.exclusive(`session\0${path.resolve(workspace)}\0${sessionId}`, async () => {
      const session = await this.get(workspace, sessionId);
      if (session.status !== "active") throw sessionConflict("rotated sessions are read-only");
      const key = this.turnKey(workspace, sessionId);
      this.activeTurns.set(key, (this.activeTurns.get(key) ?? 0) + 1);
      return session;
    });
  }

  releaseTurn(workspace: string, sessionId: string): void {
    const key = this.turnKey(workspace, assertSessionId(sessionId));
    const count = this.activeTurns.get(key) ?? 0;
    if (count <= 1) this.activeTurns.delete(key);
    else this.activeTurns.set(key, count - 1);
  }

  private turnKey(workspace: string, sessionId: string): string {
    return `${path.resolve(workspace)}\0${sessionId}`;
  }

  private async workspaceIdentity(workspace: string, now = new Date().toISOString()): Promise<WorkspaceInstanceRecord> {
    return this.exclusive(`workspace\0${path.resolve(workspace)}`, async () => {
      await ensureRealDirectories(workspace);
      const file = path.join(sessionsRoot(workspace), WORKSPACE_RECORD);
      try {
        const { value: raw } = await readBoundedJson(file, MAX_WORKSPACE_RECORD_BYTES);
        if (!isWorkspaceRecord(raw)) throw sessionError("workspace session identity is invalid");
        await fs.chmod(file, 0o600);
        return raw;
      } catch (error) {
        if (error instanceof OrgApiError) throw error;
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw sessionError("workspace session identity is unreadable");
      }
      const record: WorkspaceInstanceRecord = {
        schemaVersion: WORKSPACE_SCHEMA_VERSION,
        workspaceInstanceId: crypto.randomUUID(),
        createdAt: now,
      };
      await atomicWriteJson(file, record, MAX_WORKSPACE_RECORD_BYTES, nodeAtomicTurnWriteOperations);
      return record;
    });
  }

  private async readPositionStateIfPresent(
    workspace: string,
    positionId: string,
    workspaceInstanceId: string,
  ): Promise<PositionSessionState | null> {
    const file = positionFile(workspace, positionId);
    try {
      const { value: raw } = await readBoundedJson(file, MAX_POSITION_RECORD_BYTES);
      if (!isPositionState(raw, positionId, workspaceInstanceId)) {
        throw sessionError("position session state is invalid or belongs to another workspace");
      }
      await fs.chmod(file, 0o600);
      return raw;
    } catch (error) {
      if (error instanceof OrgApiError) throw error;
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw sessionError("position session state is unreadable");
    }
  }

  private async find(
    workspace: string,
    sessionId: string,
  ): Promise<{ session: WorkbenchSession; state: PositionSessionState } | null> {
    const identity = await this.workspaceIdentity(workspace);
    const root = positionsDir(workspace);
    let entries;
    try {
      entries = await fs.readdir(root, { withFileTypes: true });
    } catch {
      throw sessionError("session position index is unreadable");
    }
    if (entries.length > MAX_POSITIONS) throw sessionError("session position index exceeds its bound");
    for (const entry of entries) {
      if (entry.name.startsWith(".") && entry.name.endsWith(".tmp")) continue;
      if (!entry.isFile() || entry.isSymbolicLink() || !entry.name.endsWith(".json")) {
        throw sessionError("session position index contains an unsafe record");
      }
      const positionId = entry.name.slice(0, -5);
      if (!isPositionId(positionId)) throw sessionError("session position index contains an unsafe id");
      const state = await this.readPositionStateIfPresent(workspace, positionId, identity.workspaceInstanceId);
      const session = state?.sessions.find((candidate) => candidate.sessionId === sessionId);
      if (session && state) return { session, state };
    }
    return null;
  }

  private async exclusive<T>(key: string, action: () => Promise<T>): Promise<T> {
    const previous = this.locks.get(key) ?? Promise.resolve();
    let release!: () => void;
    const gate = new Promise<void>((resolve) => { release = resolve; });
    const tail = previous.then(() => gate);
    this.locks.set(key, tail);
    await previous;
    try {
      return await action();
    } finally {
      release();
      if (this.locks.get(key) === tail) this.locks.delete(key);
    }
  }
}
